### ISSUE TITLE
pytorch2caffe_MGN, I test the caffe model,but the result is different

### ISSUE THREAD

**Issue by xiaoranchenwai** [lwplw/reid-mgn#1]

**Comment by lwplw** [comment]
Forgot to explain, I changed the calculation method of max_pool in caffe, removed ceil, I guess it should be this reason, you can try again.

**Comment by xiaoranchenwai** [comment]
Yes,the reason is the max_pool,thank you very much.

**Comment by lwplw** [comment]
You are welcome！

**Comment by WhiteXiezx** [comment]
@xiaoranchenwai @lwplw hi, I converted the pytorch MGN model to caffemodel, when I test the caffemodel by caffe on market1501, I only got 59.39% mAP while the result  of pytorch is 87.50%. and my setting of pooling layer is `optional bool ceil_mode = 13 [default = false];`, can you help me ?

**Comment by lwplw** [comment]
> @xiaoranchenwai @lwplw hi, I converted the pytorch MGN model to caffemodel, when I test the caffemodel by caffe on market1501, I only got 59.39% mAP while the result of pytorch is 87.50%. and my setting of pooling layer is `optional bool ceil_mode = 13 [default = false];`, can you help me ?

There are CEIL and FLOOR modes in the pooling layer. If you set ceil_mode to False, you may calculate FLOOR mode and do downward integer calculation.
`
switch (round_mode_) {
  case PoolingParameter_RoundMode_CEIL:
    pooled_height_ = static_cast<int>(static_cast<float>(
        height_ + 2 * pad_h_ - kernel_h_) / stride_h_) + 1;
    pooled_width_ = static_cast<int>(static_cast<float>(
        width_ + 2 * pad_w_ - kernel_w_) / stride_w_) + 1;
    break;
  case PoolingParameter_RoundMode_FLOOR:
    pooled_height_ = static_cast<int>(floor(static_cast<float>(
        height_ + 2 * pad_h_ - kernel_h_) / stride_h_)) + 1;
    pooled_width_ = static_cast<int>(floor(static_cast<float>(
        width_ + 2 * pad_w_ - kernel_w_) / stride_w_)) + 1;
    break;
`

**Comment by vedantbhatia** [comment]
Hi, could you please tell me to what degree have you managed to replicate the results of the paper?
